FROM jenkins/jenkins:lts-jdk17

USER root
RUN apt-get update && apt-get install -y \
    curl ca-certificates gnupg git docker.io \
 && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
 && apt-get install -y nodejs \
 && node -v && npm -v \
 && docker --version \
 && apt-get clean && rm -rf /var/lib/apt/lists/*

USER jenkins
